#!/usr/bin/env bash

#NET_NAME="postgres"
NET_NAME="dockerrbaccomposed_postgres-rbac"
DNS_IP="10.0.0.72"
POSTGRES_PORT=5432
POSTGRES_USER="discs_names"
POSTGRES_PASSWORD="discs_names"

NAMING_CONVENTION_SERVICE_NAME=auth-services-postgres
NAMING_CONVENTION_DOCKER_ORG_NAME=lnls
NAMING_CONVENTION_DOCKER_RUN_NAME=naming-service-postgres
NAMING_CONVENTION_DOCKER_RUN_NAME_PSQL=${NAMING_CONVENTION_DOCKER_RUN_NAME}-psql
NAMING_CONVENTION_DOCKER_IMAGE_NAME=docker-${NAMING_CONVENTION_DOCKER_RUN_NAME}

NAMING_CONVENTION_DOCKER_VOLUME=naming-service-postgres-volume
